# Generated by Django 6.0.6 on 2026-07-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_color_habit_frequency_habit_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='goal_type',
            field=models.CharField(choices=[('simple', 'Simple completion'), ('time', 'Time-based')], default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='habit',
            name='target_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='timer_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
