# Generated by Django 6.0.6 on 2026-07-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='color',
            field=models.CharField(blank=True, default='coffee', max_length=50),
        ),
        migrations.AddField(
            model_name='habit',
            name='frequency',
            field=models.CharField(default='Daily', max_length=50),
        ),
        migrations.AddField(
            model_name='habit',
            name='goal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='habit',
            name='mood_tag',
            field=models.CharField(default='Calm', max_length=50),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='time_of_day',
            field=models.CharField(default='Morning', max_length=50),
        ),
    ]
